# Generated by Django 5.1 on 2024-08-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userdetails_options_userdetails_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
